const express = require('express');
const router = express.Router();
const { prisma } = require('../db.cjs');
const { authMiddleware } = require('../auth.cjs');
const { recordActivity } = require('../activity.cjs');
router.use(authMiddleware(['doctor', 'nurse', 'admin', 'reception']));

router.get('/patients', async (req, res, next) => { try { const search = String(req.query.search || '').trim(); const where = search ? { OR: [{ name: { contains: search, mode: 'insensitive' } }, { email: { contains: search, mode: 'insensitive' } }, { phone: { contains: search, mode: 'insensitive' } }] } : {}; res.json({ patients: await prisma.patient.findMany({ where, orderBy: { registrationDate: 'desc' } }) }); } catch (error) { next(error); } });
router.post('/patients', async (req, res, next) => { try { if (!['admin', 'reception'].includes(req.user.role)) return res.status(403).json({ error: 'Only reception staff or administrators can register patients' }); const { name, email, date_of_birth, gender, contact_address, phone, next_of_kin, next_of_kin_phone, blood_group, known_allergies } = req.body; if (!name || !email || !phone) return res.status(400).json({ error: 'name, email and phone are required' }); const patient = await prisma.patient.create({ data: { name, email: email.trim().toLowerCase(), dateOfBirth: date_of_birth, gender, contactAddress: contact_address, phone, nextOfKin: next_of_kin, nextOfKinPhone: next_of_kin_phone, bloodGroup: blood_group, knownAllergies: known_allergies } }); await recordActivity({ user: req.user, action: 'CREATE', entity: 'Patient', entityId: patient.id, details: `Registered patient ${name}` }); res.status(201).json({ patient }); } catch (error) { res.status(409).json({ error: 'A patient with that email already exists' }); } });
router.get('/consultations', async (req, res, next) => { try { const where = {}; if (req.user.role === 'doctor') where.doctorId = req.user.doctor_id || String(req.user.id); if (req.query.patient_id) where.patientId = Number(req.query.patient_id); const consultations = await prisma.consultation.findMany({ where, include: { patient: true }, orderBy: { consultationDate: 'desc' } }); res.json({ consultations }); } catch (error) { next(error); } });
router.post('/consultations', authMiddleware('doctor'), async (req, res, next) => { try { const { patient_id, appointment_id, presenting_complaint, clinical_findings, diagnosis, treatment_prescribed, notes } = req.body; if (!patient_id || !diagnosis) return res.status(400).json({ error: 'patient_id and diagnosis are required' }); const consultation = await prisma.consultation.create({ data: { patientId: Number(patient_id), doctorId: req.user.doctor_id || String(req.user.id), appointmentId: appointment_id ? Number(appointment_id) : null, presentingComplaint: presenting_complaint, clinicalFindings: clinical_findings, diagnosis, treatmentPrescribed: treatment_prescribed, notes } }); if (appointment_id) await prisma.appointment.update({ where: { id: Number(appointment_id) }, data: { status: 'completed', consultationNotes: notes || diagnosis } }); await recordActivity({ user: req.user, action: 'CREATE', entity: 'Consultation', entityId: consultation.id, details: `Recorded consultation for patient ${patient_id}` }); res.status(201).json({ consultation }); } catch (error) { next(error); } });
router.get('/investigations', async (req, res, next) => { try { res.json({ investigations: await prisma.investigation.findMany({ include: { patient: true }, orderBy: { dateRequested: 'desc' } }) }); } catch (error) { next(error); } });
router.post('/investigations', authMiddleware('doctor'), async (req, res, next) => { try { const { patient_id, consultation_id, test_type } = req.body; if (!patient_id || !test_type) return res.status(400).json({ error: 'patient_id and test_type are required' }); const investigation = await prisma.investigation.create({ data: { patientId: Number(patient_id), consultationId: consultation_id ? Number(consultation_id) : null, requestedBy: req.user.doctor_id || String(req.user.id), testType: test_type } }); await recordActivity({ user: req.user, action: 'CREATE', entity: 'Investigation', entityId: investigation.id, details: `Requested ${test_type}` }); res.status(201).json({ investigation }); } catch (error) { next(error); } });
router.patch('/investigations/:id', async (req, res, next) => { try { if (!['admin', 'doctor'].includes(req.user.role)) return res.status(403).json({ error: 'Forbidden' }); if (!req.body.result_summary) return res.status(400).json({ error: 'result_summary is required' }); const investigation = await prisma.investigation.update({ where: { id: Number(req.params.id) }, data: { resultSummary: req.body.result_summary, dateResultEntered: new Date() } }); await recordActivity({ user: req.user, action: 'UPDATE', entity: 'Investigation', entityId: req.params.id, details: 'Investigation result entered' }); res.json({ investigation }); } catch (error) { next(error); } });
router.get('/observations', async (req, res, next) => { try { res.json({ observations: await prisma.observation.findMany({ include: { patient: true }, orderBy: { recordedAt: 'desc' } }) }); } catch (error) { next(error); } });
router.post('/observations', authMiddleware('nurse'), async (req, res, next) => { try { const { patient_id, consultation_id, temperature, blood_pressure, pulse, respiratory_rate, notes } = req.body; if (!patient_id) return res.status(400).json({ error: 'patient_id is required' }); const observation = await prisma.observation.create({ data: { patientId: Number(patient_id), nurseId: Number(req.user.user_id || req.user.id), consultationId: consultation_id ? Number(consultation_id) : null, temperature, bloodPressure: blood_pressure, pulse, respiratoryRate: respiratory_rate, notes } }); await recordActivity({ user: req.user, action: 'CREATE', entity: 'Observation', entityId: observation.id, details: `Recorded observations for patient ${patient_id}` }); res.status(201).json({ observation }); } catch (error) { next(error); } });
module.exports = router;
